# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-12 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='Description', max_length=1000),
        ),
    ]
